### PR TITLE
Appveyor + Mingw hack

### PR DESCRIPTION
**Pull request by FredrikNoren**
Here's a temporary workaround for MinGW. Once https://github.com/alexcrichton/cmake-rs/issues/3 this should be removed.

### CODE REVIEW

**Comment by FredrikNoren** [comment]
Looks like it works but the test fails with the structs being of an unexpected size. Not sure what the purpose of those tests are though, maybe we can remove them?

**Comment by Eljay** [comment]
Ah the sanity test is wrong for 32-bit, whoops. `AiCamera` should be 1080 bytes.

The other test failure is in `aistring_long_str_fail`, which is expected to panic but doesn't work properly because MSVC 32-bit builds don't support unwinding (see rust-lang/rust#25869).

**Comment by FredrikNoren** [comment]
Ah I see. Fixed the sanity thing for 32bit and made the string test conditional on msvc 32bit

**Comment by FredrikNoren** [comment]
Alright merging as it's at least better than nothing, hope that's ok

**Pull request merged**
